// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelDelivery } from "./ChannelDelivery";
import type { ChannelPriority } from "./ChannelPriority";
import type { ChannelSenderKind } from "./ChannelSenderKind";

export type ThreadChannelMessageInput = { id?: string, channel: string, sender: string, senderKind: ChannelSenderKind, text: string, preview?: string, priority: ChannelPriority, delivery: ChannelDelivery, modelText?: string, createdAtMs?: bigint, };
