// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolResultRawRef = { rawRef: string, byteLen: bigint, sha256?: string, mime: string, redaction: string, retention: string, };
